package com.jpa.demo.entities;

import javax.persistence.*;

@Entity
@NamedQuery(name="Customer.findByFirstAndLastName",query = "select c from Customer c where c.firstName= ?1 and c.lastName= ?2")
// add this method to repository as well
@Table(name = "customers")
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "customer_id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_Name")
    private String lastName;

    // for JPA - protected can be accessed by classes in the package and subclasses outside the package , unlike default which has only visibility at package level
    protected Customer() {}
    //id is auto generated by JPA so we dont need set ID in customer while saving
    public Customer(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    // for display purposes while retrieving
    public Customer(Long id, String firstName, String lastName) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return String.format(
                "Customer[id=%d, firstName='%s', lastName='%s']",
                id, firstName, lastName);
    }
}
